### ISSUE TITLE
Twig code hard to read when using Dark theme

### ISSUE THREAD

**Issue by o-alquimista** [pulse00/Twig-Eclipse-Plugin#103]
As you can see in the screenshot, the Twig code is so dark, it almost disappears among the HTML lines. All I did was changing to the Dark theme in `Preferences > General > Appearance > Theme`. Is it possible to improve on this?

![Captura de tela de 2020-09-13 22-09-01](https://user-images.githubusercontent.com/25424263/93033770-0c9fdd80-f60e-11ea-9865-0dbe463d29a2.png)

**Comment by borisParis1** [comment]
Bonjour !
Good morning!
I Choose Dark Theme in Eclipse and i've installed the Twig plugin, **Twig Editor Feature v2.1.1** .
But i've had the same problem.
So, i've installed the [Eclipse Color Theme plugin](https://marketplace.eclipse.org/content/eclipse-color-theme) and choose my favorite theme.
Thanks to that, the issue is fixed even if after you uninstall this plugin.
